/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *Bksp;
  GtkWidget *seven;
  GtkWidget *four;
  GtkWidget *Five;
  GtkWidget *dot;
  GtkWidget *mul;
  GtkWidget *Nine;
  GtkWidget *Eight;
  GtkWidget *Six;
  GtkWidget *plus;
  GtkWidget *sub;
  GtkWidget *three;
  GtkWidget *two;
  GtkWidget *one;
  GtkWidget *Zero;
  GtkWidget *equal;
  GtkWidget *Div;
  GtkWidget *plusminus;
  GtkWidget *clear;
  GtkWidget *CE;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 112, 48);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  Bksp = gtk_button_new_with_mnemonic (_("Bksp"));
  gtk_widget_show (Bksp);
  gtk_fixed_put (GTK_FIXED (fixed1), Bksp, 16, 136);
  gtk_widget_set_size_request (Bksp, 70, 29);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 16, 192);
  gtk_widget_set_size_request (seven, 70, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 16, 240);
  gtk_widget_set_size_request (four, 70, 29);

  Five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (Five);
  gtk_fixed_put (GTK_FIXED (fixed1), Five, 96, 240);
  gtk_widget_set_size_request (Five, 79, 29);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 104, 320);
  gtk_widget_set_size_request (dot, 78, 29);

  mul = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed1), mul, 272, 240);
  gtk_widget_set_size_request (mul, 78, 29);

  Nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (Nine);
  gtk_fixed_put (GTK_FIXED (fixed1), Nine, 184, 192);
  gtk_widget_set_size_request (Nine, 70, 29);

  Eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (Eight);
  gtk_fixed_put (GTK_FIXED (fixed1), Eight, 96, 192);
  gtk_widget_set_size_request (Eight, 70, 29);

  Six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (Six);
  gtk_fixed_put (GTK_FIXED (fixed1), Six, 184, 240);
  gtk_widget_set_size_request (Six, 79, 29);

  plus = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (plus);
  gtk_fixed_put (GTK_FIXED (fixed1), plus, 280, 320);
  gtk_widget_set_size_request (plus, 78, 29);

  sub = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (sub);
  gtk_fixed_put (GTK_FIXED (fixed1), sub, 272, 280);
  gtk_widget_set_size_request (sub, 79, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 184, 280);
  gtk_widget_set_size_request (three, 79, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 96, 280);
  gtk_widget_set_size_request (two, 78, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 8, 280);
  gtk_widget_set_size_request (one, 79, 29);

  Zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (Zero);
  gtk_fixed_put (GTK_FIXED (fixed1), Zero, 8, 320);
  gtk_widget_set_size_request (Zero, 79, 29);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 192, 320);
  gtk_widget_set_size_request (equal, 79, 29);

  Div = gtk_button_new_with_mnemonic (_("\303\267"));
  gtk_widget_show (Div);
  gtk_fixed_put (GTK_FIXED (fixed1), Div, 272, 192);
  gtk_widget_set_size_request (Div, 69, 29);

  plusminus = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (plusminus);
  gtk_fixed_put (GTK_FIXED (fixed1), plusminus, 272, 136);
  gtk_widget_set_size_request (plusminus, 69, 29);

  clear = gtk_button_new_with_mnemonic (_("Clr"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 184, 136);
  gtk_widget_set_size_request (clear, 70, 29);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 104, 136);
  gtk_widget_set_size_request (CE, 69, 29);

  g_signal_connect ((gpointer) Bksp, "clicked",
                    G_CALLBACK (on_Bksp_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) Five, "clicked",
                    G_CALLBACK (on_Five_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) Nine, "clicked",
                    G_CALLBACK (on_Nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) Eight, "clicked",
                    G_CALLBACK (on_Eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) Six, "clicked",
                    G_CALLBACK (on_Six_clicked),
                    NULL);
  g_signal_connect ((gpointer) plus, "clicked",
                    G_CALLBACK (on_plus_clicked),
                    NULL);
  g_signal_connect ((gpointer) sub, "clicked",
                    G_CALLBACK (on_sub_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) Zero, "clicked",
                    G_CALLBACK (on_Zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) Div, "clicked",
                    G_CALLBACK (on_Div_clicked),
                    NULL);
  g_signal_connect ((gpointer) plusminus, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) plusminus, "clicked",
                    G_CALLBACK (on_plusminus_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, Bksp, "Bksp");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, Five, "Five");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, mul, "mul");
  GLADE_HOOKUP_OBJECT (window1, Nine, "Nine");
  GLADE_HOOKUP_OBJECT (window1, Eight, "Eight");
  GLADE_HOOKUP_OBJECT (window1, Six, "Six");
  GLADE_HOOKUP_OBJECT (window1, plus, "plus");
  GLADE_HOOKUP_OBJECT (window1, sub, "sub");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, Zero, "Zero");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, Div, "Div");
  GLADE_HOOKUP_OBJECT (window1, plusminus, "plusminus");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");

  return window1;
}

